server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gaia?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #  config:
  #    import: "optional:nacos:"
  #  application:
  #    name: gaia
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: localhost:8848
  #        namespace: public
  #        group: DEFAULT_GROUP
  ##      config:
  ##        server-addr: localhost:8848
  ##        namespace: public
  ##        group: DEFAULT_GROUP
  ##        file-extension: yaml
  ##        shared-configs:
  ##          - data-id: common-${spring.profiles.active}.yaml
  ##            group: DEFAULT_GROUP
  ##            refresh: true
  #    sentinel:
  #      transport:
  #        dashboard: localhost:8858
  #      eager: true
  #      scg:
  #        fallback:
  #          mode: response
  #          response-body: '{"code":429,"message":"服务繁忙，请稍后重试"}'
  #  profiles:
  #    active: dev
#  data:
#    redis:
#      port: 6379
#      password:
#      database: 0
#      timeout: 10s
#      lettuce:
#        pool:
#          min-idle: 0
#          max-idle: 8
#          max-active: 8
#          max-wait: -1ms

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: github.grit.gaia.interfaces.rest

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    github.grit.gaia: debug
    org.springframework.cloud.openfeign: debug
    com.alibaba.nacos.client: info