version: '3.8'

networks:
  gaia-net:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.33
    container_name: gaia-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nacos_config"
      TZ: "Asia/Shanghai"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/logs:/var/log/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  redis:
    image: redis:7.0
    container_name: gaia-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data
    command: redis-server --requirepass root
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "root", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: gaia-nacos
    restart: always
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      MODE: standalone
      #      SPRING_DATASOURCE_PLATFORM: mysql
      #      NACOS_DATASOURCE_PLATFORM: mysql
      #      MYSQL_SERVICE_HOST: mysql
      #      MYSQL_SERVICE_PORT: "3306"
      #      MYSQL_SERVICE_DB_NAME: "nacos_config"
      #      MYSQL_SERVICE_USER: "root"
      #      MYSQL_SERVICE_PASSWORD: "root"
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
    volumes:
      - ./data/nacos/data:/home/nacos/data
      - ./data/nacos/logs:/home/nacos/logs
    #      - ./data/nacos/conf:/home/nacos/config
    #    depends_on:
    #      mysql:
    #        condition: service_healthy
    networks:
      - gaia-net


  minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    container_name: gaia-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_SERVER_URL: "http://localhost:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    volumes:
      - ./data/minio/data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  rocketmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: gaia-rmq-broker
    restart: always
    ports:
      - "9876:9876"       # NameServer 兼容端口
      - "10909:10909"     # Broker HA
      - "10911:10911"     # Broker 主通信端口
    environment:
      - JAVA_OPT_EXT=-server -Xms512m -Xmx512m -Xmn256m
    volumes:
      - ./data/rocketmq/store:/home/rocketmq/store
      - ./data/rocketmq/logs:/home/rocketmq/logs
    command: sh mqbroker -n localhost:9876 -c /home/rocketmq/conf/broker.conf
    healthcheck:
      test: [ "CMD-SHELL", "curl -s localhost:10911 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  rocketmq-proxy:
    image: apache/rocketmq-proxy:5.1.4
    container_name: gaia-rmq-proxy
    restart: always
    ports:
      - "8081:8081"
    environment:
      - NAMESRV_ADDR=gaia-rmq-broker:9876
    depends_on:
      - rocketmq-broker
    networks:
      - gaia-net

  rocketmq-console:
    image: styletang/rocketmq-console-ng:latest
    container_name: gaia-rmq-console
    restart: always
    ports:
      - "8180:8080"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=gaia-rmq-broker:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rocketmq-broker
    networks:
      - gaia-net

#  prometheus:
#    image: prom/prometheus:v2.46.0
#    container_name: gaia-prometheus
#    restart: always
#    ports:
#      - "${PROMETHEUS_PORT}:9090"
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./data/prometheus:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#    networks:
#      - gaia-net
#
#  grafana:
#    image: grafana/grafana:10.0.0
#    container_name: gaia-grafana
#    restart: always
#    ports:
#      - "${GRAFANA_PORT}:3000"
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
#      - GF_USERS_ALLOW_SIGN_UP=false
#    depends_on:
#      - prometheus
#    networks:
#      - gaia-net
#
#  skywalking-oap:
#    image: apache/skywalking-oap-server:8.9.1
#    container_name: gaia-skywalking-oap
#    restart: always
#    ports:
#      - "${SKYWALKING_OAP_GRPC_PORT}:11800"
#      - "${SKYWALKING_OAP_HTTP_PORT}:12800"
#    environment:
#      SW_STORAGE: elasticsearch
#      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    networks:
#      - gaia-net
#
#  skywalking-ui:
#    image: apache/skywalking-ui:8.9.1
#    container_name: gaia-skywalking-ui
#    restart: always
#    ports:
#      - "${SKYWALKING_UI_PORT}:8080"
#    environment:
#      SW_OAP_ADDRESS: skywalking-oap:${SKYWALKING_OAP_HTTP_PORT}
#    depends_on:
#      - skywalking-oap
#    networks:
#      - gaia-net
#
#  elasticsearch:
#    image: elasticsearch:7.17.9
#    container_name: gaia-elasticsearch
#    restart: always
#    ports:
#      - "${ELASTICSEARCH_PORT}:9200"
#    environment:
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:${ELASTICSEARCH_PORT}"]
#      interval: 10s
#      timeout: 10s
#      retries: 15
#    networks:
#      - gaia-net


