version: '3.8'

services:
  canal-server:
    image: canal/canal-server:latest
    container_name: canal-server
    ports:
      - "11111:11111"  # Canal server 的端口
    environment:
      - CANAL_HOME=/canal
      - CANAL_SERVER_MODE=TCP
      - CANAL_MQ_MODE=rocketmq  # 或者使用 kafka，具体根据你的需求选择
      - CANAL_INSTANCE_MODE=MYSQL
    volumes:
      - ./canal-instance:/canal-instance  # 挂载 Canal 实例配置文件
