services:

  mysql:
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/logs:/var/log/mysql

  redis:
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data

  nacos:
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/nacos/data:/home/nacos/data
      - ./data/nacos/logs:/home/nacos/logs
      - ./data/nacos/conf:/home/nacos/conf

  sentinel:
    ports:
      - "8858:8858"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio/data:/data

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus

  grafana:
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana

  elasticsearch:
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  skywalking-oap:
    ports:
      - "11800:11800"
      - "12800:12800"

  skywalking-ui:
    ports:
      - "8090:8080"
