version: '3.8'

networks:
  gaia-net:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.33
    container_name: gaia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - gaia-net

  redis:
    image: redis:7.0
    container_name: gaia-redis
    command: redis-server --requirepass root
    networks:
      - gaia-net

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: gaia-nacos
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      NACOS_AUTH_ENABLE: "true"
      JVM_XMS: 512m
      JVM_XMX: 512m
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gaia-net

  sentinel:
    image: bladex/sentinel-dashboard:1.8.6
    container_name: gaia-sentinel
    environment:
      JAVA_OPTS: "-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel-dashboard"
    networks:
      - gaia-net

  minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    container_name: gaia-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    networks:
      - gaia-net

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: gaia-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - gaia-net

  grafana:
    image: grafana/grafana:10.0.0
    container_name: gaia-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - gaia-net

  skywalking-oap:
    image: apache/skywalking-oap-server:8.16.0
    container_name: gaia-skywalking-oap
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - gaia-net

  skywalking-ui:
    image: apache/skywalking-ui:8.16.0
    container_name: gaia-skywalking-ui
    environment:
      SW_OAP_ADDRESS: skywalking-oap:12800
    depends_on:
      - skywalking-oap
    networks:
      - gaia-net

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: gaia-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - gaia-net

