version: '3.8'

networks:
  gaia-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  nacos_data:
  minio_data:
  prometheus_data:
  grafana_data:
  elasticsearch_data:

services:

  mysql:
    image: mysql:8.0.33
    container_name: gaia-mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "${TZ}"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/logs:/var/log/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  redis:
    image: redis:7.0
    container_name: gaia-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: gaia-nacos
    restart: always
    ports:
      - "${NACOS_PORT}:8848"
      - "${NACOS_CLUSTER_PORT_1}:9848"
      - "${NACOS_CLUSTER_PORT_2}:9849"
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: "${MYSQL_PORT}"
      MYSQL_SERVICE_DB_NAME: "${MYSQL_DATABASE}"
      MYSQL_SERVICE_USER: "${MYSQL_USER}"
      MYSQL_SERVICE_PASSWORD: "${MYSQL_PASSWORD}"
      NACOS_AUTH_ENABLE: "${NACOS_AUTH_ENABLE}"
      JVM_XMS: 512m
      JVM_XMX: 512m
    volumes:
      - ./data/nacos/data:/home/nacos/data
      - ./data/nacos/logs:/home/nacos/logs
      - ./data/nacos/conf:/home/nacos/conf
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gaia-net

  sentinel:
    image: bladex/sentinel-dashboard:1.8.6
    container_name: gaia-sentinel
    restart: always
    ports:
      - "${SENTINEL_PORT}:8858"
    environment:
      JAVA_OPTS: "-Dserver.port=${SENTINEL_PORT} -Dcsp.sentinel.dashboard.server=localhost:${SENTINEL_PORT} -Dproject.name=sentinel-dashboard"
    networks:
      - gaia-net

  minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    container_name: gaia-minio
    restart: always
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_SERVER_URL: http://localhost:${MINIO_PORT}
      MINIO_BROWSER_REDIRECT_URL: http://localhost:${MINIO_CONSOLE_PORT}
    volumes:
      - ./data/minio/data:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gaia-net

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: gaia-prometheus
    restart: always
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - gaia-net

  grafana:
    image: grafana/grafana:10.0.0
    container_name: gaia-grafana
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - gaia-net

  skywalking-oap:
    image: apache/skywalking-oap-server:8.16.0
    container_name: gaia-skywalking-oap
    restart: always
    ports:
      - "${SKYWALKING_OAP_GRPC_PORT}:11800"
      - "${SKYWALKING_OAP_HTTP_PORT}:12800"
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - gaia-net

  skywalking-ui:
    image: apache/skywalking-ui:8.16.0
    container_name: gaia-skywalking-ui
    restart: always
    ports:
      - "${SKYWALKING_UI_PORT}:8080"
    environment:
      SW_OAP_ADDRESS: skywalking-oap:${SKYWALKING_OAP_HTTP_PORT}
    depends_on:
      - skywalking-oap
    networks:
      - gaia-net

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: gaia-elasticsearch
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ELASTICSEARCH_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - gaia-net


