spring:
  application:
    name: gaia-agent
  # AI 配置 - 本地开发环境
  ai:
    dashscope:
      api-key: sk-f755ab0f995c43ffa206424bb2c43de2
      chat:
        options:
          model: qwen3-max-preview
      image:
        options:
          model: wanx-v1
