services:

  mysql:
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/logs:/var/log/mysql

  redis:
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis/data:/data

  nacos:
    ports:
      - "${NACOS_PORT}:8848"
      - "${NACOS_CLUSTER_PORT_1}:9848"
      - "${NACOS_CLUSTER_PORT_2}:9849"
    volumes:
      - ./data/nacos/data:/home/nacos/data
      - ./data/nacos/logs:/home/nacos/logs
      - ./data/nacos/conf:/home/nacos/conf

  sentinel:
    ports:
      - "${SENTINEL_PORT}:8858"

  minio:
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./data/minio/data:/data

#  prometheus:
#    ports:
#      - "${PROMETHEUS_PORT}:9090"
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./data/prometheus:/prometheus
#
#  grafana:
#    ports:
#      - "${GRAFANA_PORT}:3000"
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#
#  elasticsearch:
#    ports:
#      - "${ELASTICSEARCH_PORT}:9200"
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#
#  skywalking-oap:
#    ports:
#      - "${SKYWALKING_OAP_GRPC_PORT}:11800"
#      - "${SKYWALKING_OAP_HTTP_PORT}:12800"
#
#  skywalking-ui:
#    ports:
#      - "${SKYWALKING_UI_PORT}:8080"
